version: "3"

networks:
  search-net:

volumes:
  search-pg-data:

services:
  postgres:
    image: postgres:15.1
    container_name: search-postgres
    environment:
      POSTGRES_DB: search
      POSTGRES_USER: search_user
      POSTGRES_PASSWORD: search_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - search-pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U search_user -d search"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "4G"
    networks:
      - search-net
  search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-app
    networks:
      - search-net
    ports:
      - "8080:8080"
    depends_on:
      - postgres
