package server

import (
	"context"
	"log"

	"github.com/bufbuild/connect-go"

	pb "github.com/one-zero-eight/Search/pkg/pb/search/v1" // generated by protoc-gen-go
)

type SearchServer struct{}

func (s *SearchServer) Ping(
	ctx context.Context,
	req *connect.Request[pb.PingRequest],
) (*connect.Response[pb.PingResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&pb.PingResponse{
		Messsage: "pong",
	})
	res.Header().Set("Search-Version", "v1")
	return res, nil
}
