// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: search/v1/search.proto

package searchv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/one-zero-eight/Search/pkg/pb/search/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// SearchServiceName is the fully-qualified name of the SearchService service.
	SearchServiceName = "search.v1.SearchService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SearchServiceAddRecordProcedure is the fully-qualified name of the SearchService's AddRecord RPC.
	SearchServiceAddRecordProcedure = "/search.v1.SearchService/AddRecord"
)

// SearchServiceClient is a client for the search.v1.SearchService service.
type SearchServiceClient interface {
	AddRecord(context.Context, *connect_go.Request[v1.AddRecordRequest]) (*connect_go.Response[v1.AddRecordResponse], error)
}

// NewSearchServiceClient constructs a client for the search.v1.SearchService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSearchServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) SearchServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &searchServiceClient{
		addRecord: connect_go.NewClient[v1.AddRecordRequest, v1.AddRecordResponse](
			httpClient,
			baseURL+SearchServiceAddRecordProcedure,
			opts...,
		),
	}
}

// searchServiceClient implements SearchServiceClient.
type searchServiceClient struct {
	addRecord *connect_go.Client[v1.AddRecordRequest, v1.AddRecordResponse]
}

// AddRecord calls search.v1.SearchService.AddRecord.
func (c *searchServiceClient) AddRecord(ctx context.Context, req *connect_go.Request[v1.AddRecordRequest]) (*connect_go.Response[v1.AddRecordResponse], error) {
	return c.addRecord.CallUnary(ctx, req)
}

// SearchServiceHandler is an implementation of the search.v1.SearchService service.
type SearchServiceHandler interface {
	AddRecord(context.Context, *connect_go.Request[v1.AddRecordRequest]) (*connect_go.Response[v1.AddRecordResponse], error)
}

// NewSearchServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSearchServiceHandler(svc SearchServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(SearchServiceAddRecordProcedure, connect_go.NewUnaryHandler(
		SearchServiceAddRecordProcedure,
		svc.AddRecord,
		opts...,
	))
	return "/search.v1.SearchService/", mux
}

// UnimplementedSearchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSearchServiceHandler struct{}

func (UnimplementedSearchServiceHandler) AddRecord(context.Context, *connect_go.Request[v1.AddRecordRequest]) (*connect_go.Response[v1.AddRecordResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("search.v1.SearchService.AddRecord is not implemented"))
}
